apiVersion: apps/v1
kind: Deployment
metadata:
  name: enseignant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enseignant-service
  template:
    metadata:
      labels:
        app: enseignant-service
    spec:
      containers:
        - name: enseignant-service
          image: imagee_enseignant:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 4
---
---
apiVersion: v1
kind: Service
metadata:
  name: enseignant-service
spec:
  selector:
    app: enseignant-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer